# ANN 1_res


In [110]:
import numpy as np
from sklearn.neural_network import MLPClassifier
import math


Definindo o Dataset para as funções lógicas

In [33]:
X=np.array([[1,1],[1,0],[0,1],[0,0]])
y_and=np.array([1,0,0,0])
y_or=np.array([1,1,1,0])
y_xor=np.array([0,1,1,0])


In [46]:
ann=MLPClassifier(hidden_layer_sizes=(1,),max_iter=5000,random_state=42,activation='relu')

In [51]:
ann.fit(X,y_and)
ann.predict(X)

array([1, 0, 0, 0])

In [53]:
ann.fit(X,y_or)
ann.predict(X)

array([1, 1, 1, 0])

In [60]:
X1=np.array([[1,1],[1,1],[1,1],[1,0],[1,0],[0,1],[0,1],[0,0]])
y_xor=np.array([0,0,0,1,1,1,1,0])
ann.fit(X1,y_xor)
ann.predict(X)#não conseguimos mais que 75% de acerto com 1 perceptron apenas

array([0, 0, 1, 0])

XOR com 3 neurônios (é possível com 2)

In [102]:
ann2=MLPClassifier(hidden_layer_sizes=(3,),max_iter=5000,random_state=42,activation='relu')

In [104]:
X1=np.array([[1,1],[1,0],[0,1],[0,0]])
y_xor=np.array([0,1,1,0])
ann2.fit(X1,y_xor)
ann2.predict(X)

array([0, 1, 1, 0])

Montar uma rede com o treinamento obtido pela ann2

In [107]:
ann2.coefs_,ann2.intercepts_

([array([[-2.48497143e-26,  1.58620418e+00,  2.21059775e+00],
         [ 3.66592419e-37, -1.52201218e+00, -2.21067641e+00]]),
  array([[ 2.61960890e-08],
         [-2.41813638e+00],
         [ 3.50800618e+00]])],
 [array([-9.68190297e-01,  1.52220990e+00, -1.22461288e-04]),
  array([1.8177965])])

In [109]:
def percep(w,i,activ):
    return activ(np.inner(w,i))

In [111]:
def sig(x):
    return 1.0/(1.0+math.exp(-x))

In [112]:
def relu(x):
    if x<0:return 0.0
    else:return x

In [131]:
i1=np.array([1,1,1])
w1=np.array([-9.68190297e-01,-2.48497143e-26,3.66592419e-37])
w2=np.array([1.52220990e+00,1.58620418e+00,-1.52201218e+00])
w3=np.array([-1.22461288e-04,2.21059775e+00,-2.21067641e+00])
w4=np.array([1.8177965,2.61960890e-08,-2.41813638e+00,3.50800618e+00])

In [132]:
o1=percep(w1,i1,relu)
o2=percep(w2,i1,relu)
o3=percep(w3,i1,relu)
out=percep(w4,np.array([1,o1,o2,o3]),sig)
threshold=0.5
if out>threshold:print(1)
else:print(0)

0
