# Decision Tree_res


In [1]:
from sklearn import tree
import numpy as np

In [2]:
def get_code(treex, feature_names):
    
    '''
      mostra a decisão da árvore...adaptado de ?
    '''
    left      = treex.children_left
    right     = treex.children_right
    threshold = treex.threshold
    features  = [feature_names[i] for i in treex.feature]
    value = treex.value

    def recurse(left, right, threshold, features, node):
            if (threshold[node] != -2):
                    print ("if ( " + features[node] + " <= " + str(threshold[node]) + " ) {")
                    if left[node] != -1:
                            recurse (left, right, threshold, features,left[node])
                    print ("} else {")
                    if right[node] != -1:
                            recurse (left, right, threshold, features,right[node])
                    print( "}")
            else:
                    print( "return " + str(value[node]))

    recurse(left, right, threshold, features, 0)





In [4]:
# As features são salário, clt ou não e tempo no cargo

# Observe que não houve standardization...


X =np.array( [[1000, 1,4],
     [2000, 0,1],
     [3000, 1,2],
     [4000, 1,2],
     [5000, 0,4],
     [6000, 1,2],
     [7000, 0,1]] )                
     
Y=np.array([1,0,1,0,1,1,0]) 



clf = tree.DecisionTreeClassifier(max_depth=2,random_state=51)
clf = clf.fit(X, Y)
print(clf.predict([[500,0,12.8]]))
print(clf.feature_importances_)
get_code(clf.tree_, ["sal","clt","anos"])

#Observe que a feature tempo é totalmente classifcadora

[1]
[0. 0. 1.]
if ( anos <= 1.5 ) {
return [[2. 0.]]
} else {
if ( anos <= 3.0 ) {
return [[1. 2.]]
} else {
return [[0. 2.]]
}
}


Mude o target para a feture salário influenciar mais que as outras, mas não 100%

In [16]:
       
     
Y=np.array([0,0,0,1,0,1,1]) 



clf = tree.DecisionTreeClassifier(max_depth=2,random_state=51)
clf = clf.fit(X, Y)
print(clf.predict([[500,0,12.8]]))
print(clf.feature_importances_)
get_code(clf.tree_, ["sal","clt","anos"])


[0]
[0.5625 0.     0.4375]
if ( sal <= 3500.0 ) {
return [[3. 0.]]
} else {
if ( anos <= 3.0 ) {
return [[0. 3.]]
} else {
return [[1. 0.]]
}
}


Forçar nível único...observar a feature importance

In [17]:
clf = tree.DecisionTreeClassifier(max_depth=1,random_state=51)
clf = clf.fit(X, Y)
print(clf.predict([[500,0,12.8]]))
print(clf.feature_importances_)
get_code(clf.tree_, ["sal","clt","anos"])

[0]
[1. 0. 0.]
if ( sal <= 3500.0 ) {
return [[3. 0.]]
} else {
return [[1. 3.]]
}
