# LSTM_Keras

In [1]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.optimizers import SGD
from tensorflow import set_random_seed


Using TensorFlow backend.


In [4]:
set_random_seed(42)
np.random.seed(42)
df = pd.read_csv('http://linkededucation.com.br/temp/google_stock_price.csv')


Stock_Price
0           50.12
1           54.10
2           54.65
3           52.38
4           52.95
...           ...
3007       772.88
3008       771.07
3009       773.18
3010       771.61
3011       782.22

[3012 rows x 1 columns]

In [0]:
df['d1']=0.0
df['d2']=0.0
df['d3']=0.0
df['d4']=0.0
df['target']=0.0

df.head()

In [9]:
for i in range(1000):
  df.iloc[i,1]=df.iloc[i+1,0]
  df.iloc[i,2]=df.iloc[i+2,0]
  df.iloc[i,3]=df.iloc[i+3,0]
  df.iloc[i,4]=df.iloc[i+4,0]
  df.iloc[i,5]=df.iloc[i+5,0]
ndf=df[:1000].copy()
y=np.array(ndf['target'])
ndf=ndf.drop(columns='target',axis=1)
X=np.array(ndf)
print(X.shape)
print(X[:3])
X=X[:,:,np.newaxis]
print(X.shape)
X[:3]

(1000, 5)
[[50.12 54.1  54.65 52.38 52.95]
 [54.1  54.65 52.38 52.95 53.9 ]
 [54.65 52.38 52.95 53.9  53.02]]
(1000, 5, 1)


array([[[50.12],
        [54.1 ],
        [54.65],
        [52.38],
        [52.95]],

       [[54.1 ],
        [54.65],
        [52.38],
        [52.95],
        [53.9 ]],

       [[54.65],
        [52.38],
        [52.95],
        [53.9 ],
        [53.02]]])

In [10]:
model = Sequential()
model.add(LSTM(100, activation='relu', input_shape=(5, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=200, verbose=1)





Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Epoch 1/200





1000/1000 [==============================] - 1s 1ms/step - loss: 34764.1745
Epoch 2/200
1000/1000 [==============================] - 0s 236us/step - loss: 223.6163
Epoch 3/200
1000/1000 [==============================] - 0s 228us/step - loss: 51.7996
Epoch 4/200
1000/1000 [==============================] - 0s 255us/step - loss: 46.5833
Epoch 5/200
1000/1000 [==============================] - 0s 237us/step - loss: 38.7129
Epoch 6/200
1000/1000 [==============================] - 0s 226us/step - loss: 42.3365
Epoch 7/200
1000/1000 [==============================] - 0s 256us/step - loss: 35.6865
Epoch 8/200
1000/1000 [==============================] - 0s 253us/step - loss: 35.1310
Epoch 9/200
1000/1000 [==============================] - 0s 239us/step - loss: 39.0411
Epoch 10/200
1000/1000 [==============================] - 0s 237us/step - loss: 32.2741
Epoch 11/200
1000/100