# Simple RNN

In [1]:
from keras.models import Sequential
from keras.layers import SimpleRNN
from keras import optimizers
import numpy as np
import random
from tensorflow import set_random_seed
import numpy as np


Using TensorFlow backend.


In [0]:
set_random_seed(42)
np.random.seed(42)
random.seed(42)
X_train=[]
Y_train=[]
for i in range(500):
  i=random.randint(0,50)
  X_train.append([[i],[i+1]])
  Y_train.append([i+2])
  
X_train=np.array(X_train)
Y_train=np.array(Y_train)


In [3]:
# create and fit the SimpleRNN model
model = Sequential()
model.add(SimpleRNN(units=1,activation=None,input_shape=(None, 
    1)))
model.compile(loss='mean_squared_error', optimizer='rmsprop')
model.fit(X_train, Y_train, epochs=200,batch_size=10)









Epoch 1/200





500/500 [==============================] - 1s 2ms/step - loss: 3981.4590
Epoch 2/200
500/500 [==============================] - 0s 114us/step - loss: 3377.8336
Epoch 3/200
500/500 [==============================] - 0s 110us/step - loss: 2835.7600
Epoch 4/200
500/500 [==============================] - 0s 112us/step - loss: 2379.1662
Epoch 5/200
500/500 [==============================] - 0s 104us/step - loss: 1960.0414
Epoch 6/200
500/500 [==============================] - 0s 102us/step - loss: 1601.5631
Epoch 7/200
500/500 [==============================] - 0s 116us/step - loss: 1279.9760
Epoch 8/200
500/500 [==============================] - 0s 109us/step - loss: 1008.1852
Epoch 9/200
500/500 [==============================] - 0s 107us/step - loss: 772.7302
Epoch 10/200
500/500 [==============================] - 0s 108us/step - loss: 579.4261
Epoch 11/200
500/500 [==============================] - 0s 118us/step - loss: 416.3464
Epoch 12/200
500/500 [============

In [4]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.get_weights()

[array([[0.9054703]], dtype=float32),
 array([[0.10439815]], dtype=float32),
 array([0.99077886], dtype=float32)]

In [6]:
model.predict([[[[1],[2]]]])

array([[2.9996843]], dtype=float32)