# Regressão logística_2_res

In [1]:
import pandas as pd
import numpy as np
import math
from sklearn.linear_model import LogisticRegression

In [21]:
df=pd.read_csv('c:\\dados\\banknotes.txt',names=['f1','f2','f3','f4','fraude'])

In [22]:
df.tail()

f1        f2       f3       f4  fraude
1367  0.40614   1.34920  -1.4501 -0.55949       1
1368 -1.38870  -4.87730   6.4774  0.34179       1
1369 -3.75030 -13.45860  17.5932 -2.77710       1
1370 -3.56370  -8.38270  12.3930 -1.28230       1
1371 -2.54190  -0.65804   2.6842  1.19520       1

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
f1        1372 non-null float64
f2        1372 non-null float64
f3        1372 non-null float64
f4        1372 non-null float64
fraude    1372 non-null int64
dtypes: float64(4), int64(1)
memory usage: 53.7 KB


A amostra é balanceada em positivos e negativos? Dica: use .value_counts() na série do target

In [24]:
df['fraude'].value_counts()

0    762
1    610
Name: fraude, dtype: int64

In [25]:
X=np.zeros((len(df),4))
X[:,0]=df['f1']
X[:,1]=df['f2']
X[:,2]=df['f3']
X[:,3]=df['f4']
y=np.array(df['fraude'])
X[:3]

array([[ 3.6216 ,  8.6661 , -2.8073 , -0.44699],
       [ 4.5459 ,  8.1674 , -2.4586 , -1.4621 ],
       [ 3.866  , -2.6383 ,  1.9242 ,  0.10645]])

In [26]:
#criar o classificador
rl=LogisticRegression(solver='lbfgs')

In [27]:
#Treinar
rl.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [28]:
#predição
ye=rl.predict(X)

In [29]:
#Acurácia
certos=0
for i in range(len(y)):
    if int(ye[i])==int(y[i]):certos+=1
print(certos/len(y))

0.9897959183673469


In [30]:
#coeficientes
rl.intercept_,rl.coef_

(array([3.73883455]),
 array([[-3.36496558, -1.88765064, -2.30699401, -0.08893876]]))

0.9905247813411079
