# Regressão logística_2

In [2]:
import pandas as pd
import numpy as np
import math
from sklearn.linear_model import LogisticRegression

In [3]:
df=pd.read_csv('c:\\dados\\banknotes.txt',names=['f1','f2','f3','f4','fraude'])

In [4]:
df.head()

f1      f2      f3       f4  fraude
0  3.62160  8.6661 -2.8073 -0.44699       0
1  4.54590  8.1674 -2.4586 -1.46210       0
2  3.86600 -2.6383  1.9242  0.10645       0
3  3.45660  9.5228 -4.0112 -3.59440       0
4  0.32924 -4.4552  4.5718 -0.98880       0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
f1        1372 non-null float64
f2        1372 non-null float64
f3        1372 non-null float64
f4        1372 non-null float64
fraude    1372 non-null int64
dtypes: float64(4), int64(1)
memory usage: 53.7 KB


A amostra é balanceada em positivos e negativos? Dica: use .value_counts() na série do target

0    762
1    610
Name: fraude, dtype: int64

In [25]:
#Montar matriz X e y


array([[ 3.6216 ,  8.6661 , -2.8073 , -0.44699],
       [ 4.5459 ,  8.1674 , -2.4586 , -1.4621 ],
       [ 3.866  , -2.6383 ,  1.9242 ,  0.10645]])

In [26]:
#criar o classificador


In [27]:
#Treinar


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [28]:
#predição


In [29]:
#Acurácia


0.9897959183673469


In [30]:
#coeficientes


(array([3.73883455]),
 array([[-3.36496558, -1.88765064, -2.30699401, -0.08893876]]))

0.9905247813411079
