# Autovalores_res

In [3]:
import numpy as np
m=np.array([[1,-2],[3,9]])

In [7]:
a_val,a_vet=np.linalg.eig(m)
print(a_val)
print(a_vet)

[1.83772234 8.16227766]
[[-0.92235669  0.26895177]
 [ 0.3863394  -0.96315364]]


In [10]:
np.dot(m,a_vet[:,0]),a_val[0]*a_vet[:,0]

(array([-1.6950355 ,  0.70998455]), array([-1.6950355 ,  0.70998455]))

In [11]:
np.dot(m,a_vet[:,1]),a_val[1]*a_vet[:,1]

(array([ 2.19525906, -7.86152748]), array([ 2.19525906, -7.86152748]))